### ISSUE TITLE
Set BOT_PREFIX to ! by default

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1064]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Suggesting a new feature

Currently, if the `BOT_PREFIX` is not  explicitly set in `config.py` then `Bot.bot_config.BOT_PREFIX` is not set either. IMO it should be set to the default `!`

**Comment by gbin** [comment]
I am confused: it is set to its default value here : https://github.com/errbotio/errbot/blob/master/errbot/bootstrap.py#L34

**Comment by meetmangukiya** [comment]
Hmm.. I checked this with `TestBot`
```
In [1]: from errbot.backends.test import TestBot

In [2]: testbot = TestBot()

In [3]: testbot.bot_config.BOT_PREFIX
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-b8c68c54f4ea> in <module>()
----> 1 testbot.bot_config.BOT_PREFIX

AttributeError: 'ShallowConfig' object has no attribute 'BOT_PREFIX'
```

**Comment by zoni** [comment]
You're not supposed to initialize `TestBot` by hand yourself. Manually instantiating the class will result in a lot of things not being loaded which is why you are seeing this behavior.

Proper use of the test framework (as described at http://errbot.io/en/latest/user_guide/plugin_development/testing.html#testing-your-plugins) will give you a proper bot instance to work with, including a correct BOT_PREFIX setting.
