### ISSUE TITLE
Clearer split between "disabled" and "loaded" core plugins

### ISSUE THREAD

**Issue by GenPage** [errbotio/errbot#1116]
### I am...

* [ ] Reporting a bug
* [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: Ubuntu 14.04 LTS
* Backend: Slack
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

Disabled core plugins via `config.py/CORE_PLUGINS` are still "loaded" by the bot and thus listed using `!status plugins`.

Since we are already aware of them being disabled, would it be possible to behavior to not have those Core plugins loaded at all? I view disabled plugins as being disabled by the core "Plugins" plugin management.

### Steps to reproduce

1. Disable plugins via config.py and `CORE_PLUGINS`
2. `!status plugins`

```
# If you want only a subset of the core plugins that are bundled with errbot, you can specify them here.
CORE_PLUGINS = ('ACLs', 'Health', 'Help')
```

```
ErrBot APP [11:54 PM] 
_Plugins_

┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Status ┃ Name                  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ *A*    │ ACLs                  │
├────────┼───────────────────────┤
│ *D*    │ Backup                │
├────────┼───────────────────────┤
│ *D*    │ ChatRoom              │
├────────┼───────────────────────┤
│ *D*    │ CommandNotFoundFilter │
├────────┼───────────────────────┤
│ *D*    │ Flows                 │
├────────┼───────────────────────┤
│ *A*    │ Health                │
├────────┼───────────────────────┤
│ *A*    │ Help                  │
├────────┼───────────────────────┤
│ *D*    │ Plugins               │
├────────┼───────────────────────┤
│ *D*    │ Utils                 │
├────────┼───────────────────────┤
│ *D*    │ VersionChecker        │
├────────┼───────────────────────┤
│ *C*    │ Webserver             │
└────────┴───────────────────────┘
*A* = Activated, *D* = Deactivated, *B* = Blacklisted, *C* = Needs to be configured
```

Would like to see this instead:

```
ErrBot APP [11:54 PM] 
_Plugins_

┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Status ┃ Name                  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ *A*    │ ACLs                  │
├────────┼───────────────────────┤
│ *A*    │ Health                │
├────────┼───────────────────────┤
│ *A*    │ Help                  │
└────────┴───────────────────────┘
*A* = Activated, *D* = Deactivated, *B* = Blacklisted, *C* = Needs to be configured
```

Would really appreciate the errbot team's insights and thoughts on this and if this would even be possible?

### Additional info

DigitalOcean's internal operations team is starting to use ErrBot as a framework to help streamline our internal processes to reduce reinvention of slack bots, etc. We first noticed that we did not have a need for all of the Core plugins provided in the base errbot install. As such, we disabled most of them via the `config.py` setting `CORE_PLUGINS`. Wasn't expecting them to still show up as loaded by the bot.

**Comment by zoni** [comment]
> Since we are already aware of them being disabled, would it be possible to behavior to not have those Core plugins loaded at all? I view disabled plugins as being disabled by the core "Plugins" plugin management.

I'm in agreement with you here. These core plugins are explicitly disabled by a very conscious user-decision. In my opinion, a user disabling certain core plugins does this for a good reason and likely doesn't want this plugin loaded at all, not in any way.

I'm not really familiar with this part of our plugin management because I wasn't involved in its creation, however I took a look at how it is implemented and understand why it behaves the way it does now.

We use a library called Yapsy for plugin management. Yapsy scans for valid plugins, imports their python modules and instantiates a class inside them (the `BotPlugin` class you subclass).

Later, errbot actually calls the `activate()` method on a plugin, which has to execute correctly, for a plugin to actually become active. Until that's happened, no events are actually routed to the plugin.

In our plugin management, the check for `CORE_PLUGINS` is implemented such that yapsy still scans for and loads all plugins. However, errbot just skips calling the `activate()` method, leaving it disabled/inactive.

As a result of this, the actual python module still ends up being loaded. The plugin is still registered with errbot, even if it is inactive, and thus shows up in the `!status` output as well.

I'm in agreement with @GenPage that this is unexpected behavior. I think a better design would be that Yapsy does not even import the python module for the plugin at all if it's not listed in `CORE_PLUGINS`. This is slightly more challenging to implement on a technical level, but should be quite feasible by using a custom yapsy plugin locator, something we already do for backend plugins as well.

@gbin what are your thoughts on this?

**Comment by zoni** [comment]
(Relevant piece of code lives here by the way: https://github.com/errbotio/errbot/blob/3f0eaad67e3591b1afb8fb2e7650334bfbdb4adf/errbot/plugin_manager.py#L278-L281)

**Comment by GenPage** [comment]
@zoni That is great to hear. If there is anything I can do to help/contribute just let me know, depending on work required etc.

**Comment by GenPage** [comment]
@zoni @gbin Doing some digging into the codebase. I found the example you meant for the custom plugin locator for the backend manager

https://github.com/errbotio/errbot/blob/3f0eaad67e3591b1afb8fb2e7650334bfbdb4adf/errbot/specific_plugin_manager.py#L72

Reviewing the Yapsy documentation, I see the mention of the creating a decorator chain of Managers. http://yapsy.sourceforge.net/index.html#modify-the-way-plugins-are-loaded

I'm curious on what your thoughts are how this should be implemented, either creating a separate Manager/loader for the CorePlugins, separate for the extra_bot_plugins or appending additional functionality to the existing BotPlugin class to handle re-filtering and re-loading the configured core plugins.

**Comment by zoni** [comment]
> Would it be sane and/or good practice to modify the candidates prior to loading the plugins? I propose relocating the check_enabled_core_plugin call from activate_plugin_with_version_check into update_plugin_places prior to load, and adding self.removePluginCandidate .

That looks like a very sane and easy way to do it indeed. Would you be open to implementing the necessary changes in a pull request for me to review?

**Comment by GenPage** [comment]
@zoni Totally, I'll get started on that :+1:
