### ISSUE TITLE
Bot disconnects from Slack when invoking an admin command with BOT_ASYNC=True

### ISSUE THREAD

**Issue by moyiz** [errbotio/errbot#1187]
### I am...

* [X] Reporting a bug

### I am running...

* Errbot version: 5.2.0
* OS version: Ubuntu 16.04.1 LTS
* Python version: 3.5.2
* Using a virtual environment: no

### Issue description

When `BOT_ASYNC = True` and a command is running at the background, invoking admin commands is not responsive and eventually leads to disconnections from Slack.

### Steps to reproduce

I wrote a plugin for errbot to invoke a jenkins job, wait for its completion and report the status back.
The command itself (botcmd) might run for more than 30 minutes so I have set BOT_ASYNC to True, so I could run more commands during this time. This is where it started to get weird. I have implemeted more commands and they are invoked successfully, but when I use admin commands (like: `!plugin config myplugin` to see my current configuration), errbot does not execute other commands and disconnects from Slack in about 1-2 minutes. I can see that the errbot process itself is still running.

### Additional info

In the mean time, I have commented this block in `_process_command` in `core.py`:

```python
if f._err_command_admin_only and self.bot_config.BOT_ASYNC:
    # If it is an admin command, wait until the queue is completely depleted so
    # we don't have strange concurrency issues on load/unload/updates etc...
    self.thread_pool.close()
    self.thread_pool.join()
    self.thread_pool = ThreadPool(self.bot_config.BOT_ASYNC_POOLSIZE)
```

Which seemed to solve this bug.
Maybe this behavior does not suit long running commands?

**Comment by GenPage** [comment]
Interesting edge case, I think what is happening here is since the code snippet triggers on any command that is admin_only, it'll reset the thread pool. 

But since you have a long running command holding up the pool, the admin command hangs waiting for the thread pool to close, which is waiting for the pool/queue to clear out.

As defined by the multiprocessing: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.close

```
close()
Indicate that no more data will be put on this queue by the current process. The background thread will quit once it has flushed all buffered data to the pipe.  This is called automatically when the queue is garbage collected.
```

I wonder if we can limit the scope to bot-centric commands. I believe this was done to prevent issues when plugins are loading/unloading/config updates/etc by an admin command while users are interacting with the plugin.

The best case here would be to not rely on the bot to keep that ASYNC connection open. Ideally what I would recommend instead of waiting for the jenkins job to complete after a successful POST to trigger your job, is to add a additional cmd to check the status of the job or queue up a poller within the plugin itself to check for you without holding up the message threads.

http://errbot.io/en/latest/user_guide/plugin_development/scheduling.html

**Comment by moyiz** [comment]
Thank you. I refactored it into two "short" running tasks and it works now.
Closing the issue.

PS:
I didn't present the whole picture. The plugin manages a queue and a worker. The worker pulls an item from the queue and processes it. Part of the process involves invoking a jenkins job that must be associated with this item and must be invoked only once (I cannot allow more than a single instance of this job or to let more than a single item to be processed at the same time). The easiest method to maintain this requirement was to support a locking mechanism in the plugin storage, so worker was invoked, and if the lock was free it did some work and invoked the jenkins job, waited for it to finish and according to its status did more work.
