### ISSUE TITLE
Keep plugin configuration in config.py

### ISSUE THREAD

**Issue by Fodoj** [errbotio/errbot#1373]
Excuse me if this question is very basic, but I really couldn't find the answer in documentation, existing Github issues or in the Internet.

I am trying to use Webserver plugin, which needs activation. The only way I found to activate it is to send commands to the bot. Configuration is then seems to be stored in the errbot db. Is there a way to keep configuration in config.py? I would like to store all the config as code in the repository and also package the bot together with all the relevant configuration, instead of running imperative commands _after_ bot is stared and rely on some persistence layer to just keep the config of the bot.

**Comment by sijis** [comment]
Hi,

You wont be able to store the configs within `config.py` but you have 2 alternative approaches.

1. Use an external backend (sql, redis, etc). https://errbot.readthedocs.io/en/latest/user_guide/storage_development/index.html
   There are a few plugins already available that can be used. Search the [plugin directory](https://github.com/errbotio/errbot/wiki) for `storage`.

2. You can use the backup/restore options and load settings upon launch. Refer to https://errbot.readthedocs.io/en/latest/user_guide/provisioning.html.

**Comment by Allianzcortex** [comment]
@sijis sorry to reopen it , but  what's the meaning of  `d load settings upon launch`. Im trying to run the errbot with Webserver(as webhook) from a docker which means I cannot enter the command `!plugin config {}` manually after the container is started. Do you have any ideas about this situation ? The program could work well in the local but not in docker because there will always be errors like 
`errbot.plugins.Webserver  Webserver is not configured. Forbid activation`
