### ISSUE TITLE
Plugin wiki page no longer loading

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1407]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Here about something else

### Issue description

We need to move the [Plugin Page](https://github.com/errbotio/errbot/wiki) away from the wiki, as its unable to generate the page anymore.

![Screenshot from 2020-01-18 22-46-55](https://user-images.githubusercontent.com/618177/72675043-7c8ca280-3a44-11ea-92d6-cbe32f88d086.png)

### Possible Alternatives

* Use Github Pages - https://pages.github.com/
* Split page in multiple pages
* Remove it altogether

I'm leaning towards Github Pages.

**Comment by bisco2** [comment]
I think the question is also how the list of plugins should be maintained.

Looking over the roughly 600 (!) entries on the plugin page, there are a lot of 'Hello World' plugins, some repositories are being listed  multiple times because they contain multiple plugins, but all of them with the same description, one repository (https://github.com/codebam/python-sparklebot) is a stale fork of errbot, but is listed more than 25 times

So maybe it makes more sense to maintain the plugin list by hand and ask the developers to create a merge request if they want their plugin listed?

I also think that backends should be listed on a separate page, and there are also a couple of storage-backends which might warrant a separate storage-backend page...

**Comment by Thutm** [comment]
I was just going out to look for some example plugins and ran into this issue. I think it does make sense to opt-in to the plugin directory rather than crawling for everything if there is that big of a problem. 

In my opinion, you could still crawl the repo's, but maybe look for an indicator on the repo you find before adding them to the list. (i.e. a particular branch like github pages or something?). That would allow users to "opt-in" or "publish" their plugin for the directory. You could obviously disposition the list of repo's found today and grandfather in ones that are legit. Maybe that would help keep random / test plugins from showing up on the list. Outside of that, a manual publish type thing via github issues is always a thing.

How does the crawling and indexing occur today? Is that something we could see and propose changes to?

**Comment by sijis** [comment]
@bisco2 You have some very good ideas. It probably is a question of how this list should be maintained.

@Thutm Yeah, programmatically we could do something to reduce the noise of duplicate plugins and what not. The code that generates all that is in https://github.com/errbotio/errbot/tree/master/tools.

**Comment by sijis** [comment]
Updated the wiki page and removed all the content.
Long term probably having an opt-in file may be worth it.
