### ISSUE TITLE
Abstract method email in errbot/errbot/backends/base.py problem with gitter plugin

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#1460]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x ] Here about something else

### I am running...

* Errbot version: 6.1.2 
* OS version: Ubuntu Focal
* Python version: 3.6.6
* Using a virtual environment: yes

### Issue description

I've upgrade my errbot version to the last one. 
I'm using gitter plugin.
When starting the bot does not work and launches this message:
"TypeError: Can't instantiate abstract class GitterPerson with abstract methods email"

The problem seems to be that gitter.py does not have an email method. It can be solved adding, for example:

    @property 
    def email(self): 
         return ""

To the code, but I'm not sure if this is the best way to solve the problem and, maybe, this method should not be and abstract property.

**Comment by nzlosh** [comment]
I tend to agree that base Person should not be an abstractmethod.  Since the change was introduced specifically for Slack purposes, the base class should implement a sane default that other backends can override if it makes sense to do so.

Gitter is being mentioned here but any errbot backends external to the core errbot repository will most likely be impacted, Discord, Mattermost and RocketChat come to mind.

@sijis What are your thoughts?

**Comment by sijis** [comment]
@nzlosh @fernand0 Not ideal that broken existing backends. I put in a PR to address it. Would you be able to verify it fixes the problem?

**Comment by fernand0** [comment]
I've installed your branch and I think it solves the problem. Thanks.
