### ISSUE TITLE
Callbacks for events

### ISSUE THREAD

**Issue by mrshu** [errbotio/errbot#474]
While I can see that `err` has a [callback for message](http://errbot.net/user_guide/plugin_development/messaging/#trigger-a-callback-with-every-message-received) there are many more events that can happen in an ordinary MUC. Just off top of my hear:
- join
- leave
- status (/me)
- kick
- topic (change/set)
- ban
- unban

and so on. Does `err` support callbacks for these events? I tried to find something like this in the codebase but while I found thing like `callback_room_joined` it seems that this event is only triggered when the bot joins a room but it won't get called when a user does so.

Moreover, would it be possible to have a 'catch-all' event callback, something like `callback_event` that would get triggered on any event?

If `err` currently does not support what I am asking for would you be open to adding it? I will gladly contribue this functionality for IRC and XMPP as those are the only two backends I have some real world experience with running bots on.

**Comment by gbin** [comment]
We have callback_room_topic and callback_presence (for the status).
Maybe the presence can be updated to encompass the join/leave/kick/ban/unban.
We also have a callback_stream for file transfers.

I am not really favorable on having a catch-all even callback simply because it would not be coherent but having a more comprehensive coverage would be awesome !

Feel free to make a proposal to add the missing events to the contract, your contribution would be greatly appreciated.

**Comment by mrshu** [comment]
> I am not really favorable on having a catch-all even callback simply because it would not be coherent but having a more comprehensive coverage would be awesome !

Well, suppose you would want to be able to do your own logging of a MUC. For that you need to catch every event that happens in the given MUC. Now if there will not be a catch-all callback then what you would have to do would be repeating a calls like `save_event('join', event)` in every single callback. This is basically the reason why I would like a catch-all callback function: so that people could decide which events to respond to with some action.

> Feel free to make a proposal to add the missing events to the contract, your contribution would be greatly appreciated.

All right, will do!

**Comment by gbin** [comment]
Any progress on this one ?

**Comment by qlixed** [comment]
I'm working on it within a fork created a few days ago.
The thing is that for some of the code require a wide restructuration, for example the join/joined event.
As per the code appears, the backends allow to create a IRCMUCRoom without joining to it, that's have no sense.
Another thing is that every time that the IRCBackEnd.query_room, create s IRCMUCRoom for ANY room that I send as a parameter, regardless I'm joined or not, that's another non-sense, mostly because the information gathering methods on IRCMUCRoom requires that we join the channel, so, for all this (and other) inconsistencies I need to change the current behavior of the join/joined mechanism.
As per I going to work with this, I will put all the relevant changes on my fork, trying to document all the behavioral changes and then we can work over it to refine all.

**Comment by zoni** [comment]
> The thing is that for some of the code require a wide restructuration, for example the join/joined event.
As per the code appears, the backends allow to create a IRCMUCRoom without joining to it, that's have no sense.
Another thing is that every time that the IRCBackEnd.query_room, create s IRCMUCRoom for ANY room that I send as a parameter, regardless I'm joined or not, that's another non-sense, mostly because the information gathering methods on IRCMUCRoom requires that we join the channel, so, for all this (and other) inconsistencies I need to change the current behavior of the join/joined mechanism.

This is by design and how it works for all backends, not just IRC. You can indeed create a MUCRoom instance for any room you name, regardless of whether or not it exists. This is why it has methods such as [exists](http://errbot.io/errbot.backends.base.html#errbot.backends.base.MUCRoom.exists) and [create](http://errbot.io/errbot.backends.base.html#errbot.backends.base.MUCRoom.create) to determine if it's an existing room and actually create it.

Similarly, on some backends (Slack and HipChat for example) it makes sense that you can [destroy](http://errbot.io/errbot.backends.base.html#errbot.backends.base.MUCRoom.destroy) a room. But on IRC that semantic doesn't really hold (I guess an IRC op could do something like that on some IRCd's, but that's an unusual usecase) so calling that method on the [IRC implementation](http://errbot.io/errbot.backends.irc.html#errbot.backends.irc.IRCMUCRoom.destroy) raises an exception.

We can debate the general design of the MUCRoom implementation separately,  but I'd ask that you not change how this API works for the time being. It's very unlikely to be accepted because (1) it would involve making changes to all the other backends in order to remain consistent (which is a lot of work to coordinate and test properly within the same release cycle) and (2) this would then cause pressure on users by being a breaking API change which forces people to update their code, and that is something that should only happen for very good reasons.

That said though, I really don't want you to feel discouraged. I'd be more than happy to help you improve the IRCMUCRoom implementation within the current design of how MUCRoom works and I don't think there's anything really preventing that.

(For example, [exists](http://errbot.io/errbot.backends.irc.html#errbot.backends.irc.IRCMUCRoom.exists) isn't really implemented properly. It actually returns whether the room is joined or not, but what it probably should do is see whether the room shows up in a `/list` query (though that's going to be problematic on a huge network such as Freenode, where you should query alis for it instead).)

**Comment by qlixed** [comment]
Well..
I understand clearly what you say. I don't want to break all things, So i
try a more "Quirurgic" aproach to the changes.
I not going to mess up with the API. I'm just try to put some hacks to
improve the current behavior.
Then I will make some test with twisted to see if we can make a new IRC
Backend.
The python-irc is a little mess :)

**Comment by piotrekjanisz** [comment]
Any updates on this? I really need a functionality to have a callback when a user enters a room. Currently I don't see how I can achieve that.

**Comment by gbin** [comment]
This is done.

**Comment by sijis** [comment]
There are a lot of callbacks since this was first opened.
http://errbot.io/en/latest/errbot.botplugin.html#module-errbot.botplugin

It seems something in there should fit the need. If tha'ts not the case, please open a new issue.
