### ISSUE TITLE
http://errbot.net/ not working

### ISSUE THREAD

**Issue by robbiebyrd** [errbotio/errbot#542]
Getting a 404 from github

**Comment by zoni** [comment]
We just moved the repository from `gbin/err` to `errbotio/errbot` and it appears that did not migrate the GitHub pages correctly. Doh! To make matters worse I didn't notice because, even though I have monitoring on the domain that correctly picked up on the 404, it only went into a *warning* state rather than *critical* so I didn't get a notification. :cry: 

I've pushed a new build to the `gh-pages` branch and everything has been restored now. Thanks for bringing this to our attention!
