### ISSUE TITLE
Hide or Disable Core Plugins

### ISSUE THREAD

**Issue by bporter2387** [errbotio/errbot#580]
I understand I can disable commands from running, but I want to remove them from the !help menu altogether. Is there a way I can disable core plugins? or is removing them from the core_plugins folder the only way? I would like a completely custom !help menu.

Thanks!

**Comment by gbin** [comment]
Yes, it was in the plans actually we should revive this, see the discussion was from the chat for details.

We would add a list of bundled_plugins to the config. If it is not set by default it is the full list otherwise this is the set you want to enable.
I'll take it if it is ok with @jamesob.
---
if we had an option : no bundled plugins ?

jamesob Nov 12 22:05
lol, but if we're going that route then why don't we just have a plugins_enabled list?
I mean yes, sure, the no_bundled_plugins would suit my purposes just fine
so I'd certainly take it
but it feels very special-casey

gbin Nov 12 22:05
not really
what if you want a very custom errbot

jamesob Nov 12 22:06
plugins_enabled = ['my_custom_plugin']

gbin Nov 12 22:06
the no_bundled_plugins would kick out the bundled plugins from the search path

jamesob Nov 12 22:07
but in my case, I want to use help plugin
so... what would I do?
basically I want to use help but no other bundled plugins
so no_bundled_plugins kinda screws me unless there's a way to specify "oh yeah but include help"
hence enabled_plugins 

gbin Nov 12 22:08
ha simply... bundled_plugins

jamesob Nov 12 22:08
bundled_plugins = ['help']?

gbin Nov 12 22:08
that is not about blacklisting, but adding one by one which bundled plugins you want on the search path
yep

jamesob Nov 12 22:09
sure, that'd be fine too

gbin Nov 12 22:09
it doesn't brake any chatops feature
if it is not set, it adds the root of them : https://github.com/errbotio/errbot/tree/master/errbot/core_plugins
but then we need to split them into subdirs
(which makes sense because it is a mess)
and then selectively add to the search path the ones your specify by BUNDLED_PLUGINS
it makes sense for a lot of stuff

jamesob Nov 12 22:12
+1

gbin Nov 12 22:12
they are called core plugins
so maybe CORE_PLUGINS=['help', 'backup', ...]
this thing is set there : https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L23
Do you want to give it a shot ?

jamesob Nov 12 22:17
yeah, sure

**Comment by gbin** [comment]
Can you give it a try ? #583 
@jamesob any comments are welcome on the PR !

**Comment by gbin** [comment]
This has been merged.
