### ISSUE TITLE
errbot link for upgrade

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#628]
Hello,

my errbot is announcing the new version with this message:
Version 3.2.3 of err is available. http://pypi.python.org/pypi/err/3.2.3. You can disable this check by doing !plugin blacklist VersionChecker
But the link seems not to be working?

**Comment by zoni** [comment]
Oh darn! We renamed the package from err to errbot (but left `err` as a dummy package with a dependency on `errbot`) and forgot to update the link in the version checker. I just fixed that in 3bafa18fac257d58f287a69b1c64f52e0bdafa98.

@gbin maybe we should release a version 3.2.3 of our dummy package so that the link works correctly?

**Comment by gbin** [comment]
I quickly bumped it straight from pypi, I am changing this message now.
