### ISSUE TITLE
Table rendering broken for repos

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#639]
![image](https://cloud.githubusercontent.com/assets/975564/13552753/6ab2171e-e324-11e5-8c7f-798f4ea52ca9.png)

This is on our test instance on gitter

**Comment by gbin** [comment]
My quick analysis: desctription is multiline and the template doesn't draw the empty cells on the left

**Comment by ifigotin** [comment]
The multi-line support for tables is usually done with the help of ` '<br>' `html tag (e.g. http://stackoverflow.com/questions/11700487/newline-in-markdown-table).

If we support` <br>`, then errbot/rendering/ansi.py needs to be modified in order to convert `<br>`s into appropriate number of rows when rendering a table.

However, currently, I can see that my `<br>` tags get encoded by the time it gets to errbot/rendering:translate. I.e. in Markdown, one of the TreeProcessors converts `<br/>`, first to this "def&lt;br/&gt;abc", then to this "def\x02wzxhzdk:0\x03abc", so by the time we get the xml object it no longer has `<br>`, but instead it has HTML_PLACEHOLDER defined in Markdown/extensions/util.py

**Comment by ifigotin** [comment]
It turned out to be a little bit more involved. What I think I'd need is to understand how the Markdown   [Extension API](https://pythonhosted.org/Markdown/extensions/api.html) works. Perhaps I'd need an Inline processor that would keep line breaks the same so that by the time it gets to errbot/rendering:translate I still have these tags so I could render the multiline cells appropriately.
