### ISSUE TITLE
error getting Slack room occupants

### ISSUE THREAD

**Issue by aherok** [errbotio/errbot#709]
Hi!
I'm playing with errbot connected to Slack and I encountered problem when trying to fetch room occupants from inside `callback_message` method.
Calling `message.to.occupants` gives me error

```
*** Exception: This is not a Slack user or bot id: aherok (should start with U or B)
```

I believe the problem lies here: 
https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L824
when property method `occupants` is creating instances of `SlackRoomOccupant` class, but it's passing wrong parameters - user's `username` and channel's `_name` instead of their IDs used by Slack API.

So that given line should probably be changed to:
```
return [SlackRoomOccupant(self.sc, m, self.id, self._bot) for m in members]
```

I'm hoping I haven't done any mistake. If I did, please tell me what I'm doing wrong.
Cheers!

**Comment by zoni** [comment]
Thanks for diving into this bug and pointing out the source of the problem, you were spot on! This is fixed in 484ad7286274880576d8a67fe089a64a957e03ec now.

We are planning to do a `4.1` release quite soon (I'd say within two to three weeks at most) so this will be included in a stable release relatively soon.
