### ISSUE TITLE
Handle irc.client.MessageTooLong exception ?

### ISSUE THREAD

**Issue by Djiit** [errbotio/errbot#721]
When using the IRC Backend, each message sent by the bot *shoud not* be longer than 512 bytes (including CR+LF at the end of the message).
The python IRC lib used by the core backend raise a `irc.client.MessageTooLong` exception (https://github.com/jaraco/irc/blob/master/irc/client.py#L101-L102) when this happens, based on the actual spec (https://tools.ietf.org/html/rfc2812#page-6):

> IRC messages are always lines of characters terminated with a CR-LF
   (Carriage Return - Line Feed) pair, and these messages SHALL NOT
   exceed 512 characters in length, counting all characters including
   the trailing CR-LF. Thus, there are 510 characters maximum allowed
   for the command and its parameters.  There is no provision for
   continuation of message lines.  See section 6 for more details about
   current implementations.

A good workaround is to use the standard `textwrap` module like described in this comment: https://github.com/pteichman/cobe/issues/14#issuecomment-47043000

Should we handle this exception for the user ? In the rare case you have to send a massive amount of data and didn't split the message yourself (or maybe didn't see it coming), maybe Errbot could handle it itself with a default wrapping of 510 char. per lines and then send multiple messages.

**Comment by qlixed** [comment]
Checking that we also need to check if the user sends a CR without a LF or an LF without the CR and change it to a CRLF pair, so we can get multiple messages in chunck compatible with the standard, so if I send:

"This is\na multiline text"

This need to be changed to:

"This is\r\na multiline message"

Also we can split That in two messages to sent as they should leaving:

["This is", "a multiline message"]

And maybe sent them as independient messages?

**Comment by zoni** [comment]
Errbot already splits messages up when they are too long, but the [default size](https://github.com/errbotio/errbot/blob/4.1.3/errbot/errBot.py#L55-L56) is a lot bigger than 512 bytes.

The fix for this is to clamp `MESSAGE_SIZE_LIMIT` to an appropriate maximum value when using IRC. The Telegram backend [also does this](https://github.com/errbotio/errbot/blob/4.1.3/errbot/backends/telegram_messenger.py#L181), [as does Slack](https://github.com/errbotio/errbot/blob/4.1.3/errbot/backends/slack.py#L497) (but the way it's done with Telegram is more suitable here).

--------

@qlixed: Could you open a separate issue about the CR vs CRLF vs LF thing?

**Comment by zoni** [comment]
Fixed via #858
