### ISSUE TITLE
shelf storage ends db.db

### ISSUE THREAD

**Issue by yolkov** [errbotio/errbot#750]
errbot -v
Errbot version 4.1.3

ls -1 /var/lib/err/ | grep db
ACLS.db.db
Backup.db.db
ChatRoom.db.db
core.db.db
Flows.db.db
Health.db.db
Help.db.db
PluginAvitoStash.db.db
Plugins.db.db
repomgr.db.db
slack_backend.db.db
Utils.db.db
VersionChecker.db.db
Webserver.db.db

**Comment by zoni** [comment]
There is unfortunately not a lot we can do about this. This is caused by a subtle difference in berkdb vs. gdbm, where one automatically appends the `.db` suffix and the other one doesn't. There's more details about this in e75b5e89c0b89253e86ea95cf43003b67edfdf7e.

If you have a good suggestion for how to deal with this, I'd love to hear about it, but otherwise there isn't anything we can do to prevent this.
