### ISSUE TITLE
deny all acl

### ISSUE THREAD

**Issue by murinicanor** [errbotio/errbot#775]
hi,

as far as i understand the ACL syntax, the default acl
`ACCESS_CONTROLS_DEFAULT = { '*': {'allowusers': BOT_ADMINS } }`

should deny any commands to anyone but the admins. but this appears to have no effect, the log output when running !help is for example:

> Matching ACL {'*': {'allowusers': ('muri@foo.bar',)}} against username something@conference.bar.baz for command Help:about

and the command works.
how do i restrict all the commands, so that only the ones i explicitly allow are working for users?

**Comment by zoni** [comment]
When `allowusers` is set, anyone not listed in it will be [denied access](https://github.com/errbotio/errbot/blob/4.1/errbot/core_plugins/acls.py#L77-L78) yes.

It's a subtle one but the issue here appears to be that you misconfigured `ACCESS_CONTROLS_DEFAULT`. It should instead be:

`ACCESS_CONTROLS_DEFAULT = {'allowusers': BOT_ADMINS }`.

I think it might be a good idea for us to log a warning when unknown keys are present in the ACL. It would have complained about finding a `*` here in this case, so you'd spot syntax errors more quickly.

**Comment by murinicanor** [comment]
ah, oke, i misunderstood the syntax of the _DEFAULT rule. maybe this example could be inserted into the explanation in the default configy.py?
thanks a lot for your help (and for errbot)!
