### ISSUE TITLE
backend tester fails on Slack

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#777]
you can try it by installing https://github.com/errbotio/err-backend-tester

On a private channel, if you do !private, it fails with:
```
FAILED mess.to should implement equal correctly and resolve to the bot
```
It means the SlackPerson representing the bot is not equal to the mess.to it receives (the bot doesn't know who it is basicallly :) )

@tynril : This is probably related to my comment on the identity comparison.

**Comment by tynril** [comment]
Fixing the SlackPerson equality check (by removing the channel id comparison), I'm getting another error:
```
yapsy_loaded_plugin_Slack_0.SlackAPIResponseError: Slack API call to im.open failed: cannot_dm_bot
```
It is caused by using `get_im_channel` on the bot `userid`. I'm going to open a PR to change the comparison back to what it used to be, though.

**Comment by tynril** [comment]
I won't put this in the equality PR because it's unrelated, but a way to "fix" the second layer of error is to implement `get_im_channel` as:

```
     def get_im_channel(self, id_):
         """Open a direct message channel to a user"""
        try:
            response = self.api_call('im.open', data={'user': id_})
            return response['channel']['id']
        except SlackAPIResponseError as e:
            if e.error == "cannot_dm_bot":
                return None
            else:
                raise e
```
But I'm not sure if that will have negative side effects.

Also, the `!public` test also fails because of:

- A bug in the test plugin (parenthesis mismatching on line 51)
- It ends up comparing a `SlackRoom` to a `SlackPerson` because `build_identifier` with a `#channel` identifier still returns a `SlackPerson` (see #778).

**Comment by gbin** [comment]
Fixed and pushed the parenthesis mismatch  :)

**Comment by gbin** [comment]
@tynril I have pushed to master the DM error fix + all the type check for the `__eq__` so at least now it fails nicely.
