### ISSUE TITLE
Slack Incoming WebHook User Not recognised

### ISSUE THREAD

**Issue by rcotgrov** [errbotio/errbot#874]
I'm using the slack back-end.

If I post to a private channel with my own Slack ID, the ERRBOT works perfectly and processes the command with my custom plugin, however I am looking to read the text from an incoming webhook based BOT that posts from another system into Slack. 

I get the following error when ERRBOT / Slack-back end attempts to read the channel message

14:31:26 ERROR    errbot.backends.slack     Cannot find user with ID B2KPV349Z

Thanks

**Comment by sijis** [comment]
It sounds like you are bumping into the same issue described at https://github.com/errbotio/errbot/issues/812. Could you confirm?

**Comment by rcotgrov** [comment]
Look's like it. Is there any fix/workaround ?

**Comment by rcotgrov** [comment]
Used 4.3 branch with debug on to provide more info. Added **** in the debug output as security measure. 

Output detail when regular Slack user posts to Slack and ERRBOT sees the event

20:40:33 DEBUG    errbot.backends.slack     Saw an event: {'channel': 'G2****NLB',
 'team': 'T0N****PG',
 'text': '!list templates',
 'ts': '1476997252.000008',
 'type': 'message',
 'user': 'U0N****LQ'}

Debug detail when a BOT posts to Slack and ERRBOT sees the event. There is quite some difference in the outputs. 

20:40:46 DEBUG    errbot.backends.slack     Saw an event: {'bot_id': 'B2****49Z',
 'channel': 'G2****NLB',
 'icons': {'emoji': ':ghost:',
           'image_64': 'https://a.slack-edge.com/d4bf/img/emoji_2015_2/apple/1f47b.png
 'subtype': 'bot_message',
 'team': 'T0N****PG',
 'text': '[via Alexa]: !list templates',
 'ts': '1476997266.000010',
 'type': 'message',
 'user_team': 'T0N****PG',
 'username': 'Bot'}

**Comment by rcotgrov** [comment]
I've tried a regular public channel too now and it does exactly the same thing.

**Comment by rcotgrov** [comment]
Have done some digging myself and can see the "Incoming Webhook" user I am using to post to Slack does not appear when ERRBOT executes effectively the "USERS.LIST" api call to determine the userid from the username. I can see that problem by looking at the Web test method of "USERS.LIST". The userid the "Incoming Webhook" user uses does not show up in the JSON returned

Therefore I have raised a question with Slack as it may be my misunderstanding that I thought all posts to a Slack Channel will have an associated userid/username entry when you call the "USERS.LIST" api call. 

In fact it could be by design "Incoming Webhook" based solutions do not get an entry in the list of users for a given Slack Channel. Of which case we would need a special code case to accommodate this (by not calling "USERS.LIST" etc..) OR simply state "Incoming Webhook" based posts on Slack are not supported and I would have to re-write the posting side of my solution. 

Thoughts ?

**Comment by rcotgrov** [comment]
Received response from Slack. My "incoming webhook" has an Integration ID and not a userid. This means it will not be found in the list of users on a given channel. Therefore the ERRBOT/SLACK code is trying to obtain a username from an "Integration ID" and this won't work. Is the code supposed to work with posts from Integration ID's ?

**Comment by zoni** [comment]
> Therefore the ERRBOT/SLACK code is trying to obtain a username from an "Integration ID" and this won't work. Is the code supposed to work with posts from Integration ID's ?

Well, yes. It just wasn't designed with this corner case in mind. So it's a bug and we should find a way to make it work.

This may or may not be trivial to fix because errbot does a fair bit of mapping back and forth between IDs and usernames to present a high-level, more abstract `Identifier` interface to plugins, but I'm certain we can make it work with some effort.

**Comment by rcotgrov** [comment]
Ok. No worries. I'm working on a project to integrate an IOT device with some IT Infrastructure and I'm up against tight timescales to produce a working demo. I'm trying to think of the best way forward. Any suggestions welcome. Perhaps I could change the posting code to use a BOT with userid/username instead. I am reluctant to do this but guess I may have too ????

**Comment by rcotgrov** [comment]
This is the response from Slack support. Thanks Audrey. 

"I think I see what happened. It seems that ERRBOT is retrieving the username from the username link, which for regular users is the URL to the user's profile page, but for an integration such as incoming webhook, it's the URL for the integration's configuration page. However, we don't state anywhere that the integration URL contains a username, but ERRBOT is blindly trying to extract a username value from the URL and when it does this for a message sent by an incoming webhook, it's getting the integration ID instead.
I was initially confused as to where you may have found information about an integration ID being a user ID, but I can see based on this setup how that could happen. Unfortunately, we don't have a link that specifically defines the integration ID and the user ID. However, the doc for the users.list method does state:
This method returns a list of all users in the team. This includes deleted/deactivated users.
An incoming webhook isn't a user so it wouldn't be applicable in this case"

**Comment by zoni** [comment]
> Perhaps I could change the posting code to use a BOT with userid/username instead. I am reluctant to do this but guess I may have too ????

While not pretty, it would certainly be a workable workaround for the time being yes. If you have any experience with Python code, I'd also be happy to give you some pointers on where to look in errbot's code to come up with a potential fix to our slack backend for this.

I will see if I can find some time to take a look this Thursday or Friday, but my life is rather busy right now so don't get your hopes up, I can't make any promises.

**Comment by rcotgrov** [comment]
Well, I have experience with Perl and like a challenge. Good way to develop some Python experience too. Some pointers would be great if you can spare the time. Thanks.

**Comment by zoni** [comment]
So as you might be aware, errbot provides identifiers that abstract away some backend specifics and provides an identifier representing a user or channel. These behave consistently across all backends.

In the case of the slack backend, that's [SlackPerson](https://github.com/errbotio/errbot/blob/9a2e3ec13dd6159cfe4d286f26ab653f389b862a/errbot/backends/slack.py#L101-L185), [SlackRoomOccupant](https://github.com/errbotio/errbot/blob/9a2e3ec13dd6159cfe4d286f26ab653f389b862a/errbot/backends/slack.py#L188-L210) and [SlackRoom](https://github.com/errbotio/errbot/blob/9a2e3ec13dd6159cfe4d286f26ab653f389b862a/errbot/backends/slack.py#L844-L1030)

When a [message is handled](https://github.com/errbotio/errbot/blob/9a2e3ec13dd6159cfe4d286f26ab653f389b862a/errbot/backends/slack.py#L390-L446) we [do some magic](https://github.com/errbotio/errbot/blob/9a2e3ec13dd6159cfe4d286f26ab653f389b862a/errbot/backends/slack.py#L435-L441) to map Slack IDs into proper identifiers.

Around there is where I think we need to look. We might need to create a new identifier (`class SlackBot(Person)` perhaps?) for these webhooks/bot users or map them to a `SlackPerson`/`SlackRoomOccupant`. The trouble will probably be that we cannot send messages ***to*** these IDs so we might need some special extra handling to deal with that case (because what happens if the bot tries to respond to such a message?)

**Comment by zoni** [comment]
@rcotgrov I had some time to delve into this today and came up with a possible implementation, see #895. If you have some time, I'd love for you to try out that branch (let me know if you need help on how to run errbot from a development branch) and report back your successes and/or failures.

I'm not 100% happy with the implementation of all the identifiers on Slack, it's a little messy, but completely rewriting and cleaning up everything is way way more work than I have time for right now. (I think the current proposed implementation in #895 would not prohibit such a refactoring from happening in the future though and believe it continues to provide a good API even if some of the internals are messy).

**Comment by rcotgrov** [comment]
Thank you. It worked!  Great job!

**Comment by zoni** [comment]
Excellent, I'm glad we got that fixed up. I'll merge that in then, and see about doing another release somewhere around the end of the month so we get that out in a stable version.
