### ISSUE TITLE
Location of config-template.py

### ISSUE THREAD

**Issue by SvenNederhoff** [errbotio/errbot#901]
In order to let us help you better, please fill out the following fields as best you can:

### I am ...
* [ ] Reporting a bug

### I am running...

* Errbot version: 4.3.4
* OS version:  Ubuntu 16:04
* Python version:  3 
* Using a virtual environment: yes

### Issue description

When you try to start errbot for the first time there is no config.py. The message say's where you can find that file. but that's a wrong location of the file.
```
14:25:58 ERROR    errbot.cli                I cannot find the config file ~/errbot/config.py 
(You can change this path with the -c parameter see --help)
14:25:58 INFO     errbot.cli                You can use the template ~/errbot/lib/python3.5/site-packages/errbot/cli.py/config-template.py as a base and copy it to ~/errbot/config.py. 
You can then customize it.
```

the correct location of the file is 
`~/errbot/lib/python3.5/site-packages/errbot/config-template.py`

### Steps to reproduce

Just install a fresh errbot without config file and start it.

**Comment by zoni** [comment]
This looks simple to fix. `cli.py` is currently taking the path to itself and appending `config-template.py` to it, causing the issue. It should instead take the *path to the directory where it is located* instead, then everything will be good.

The relevant code that does this can be found in [cli.py, line 71](https://github.com/errbotio/errbot/blob/06abf52a75c5e8ec677d4ee3a330c6f653457b52/errbot/cli.py#L71). Would you like to make a PR to fix this so that you can take credit?

**Comment by zoni** [comment]
Ping @SvenNederhoff, please let me know if you'd like to work on this or if you'd rather see us fix it ourselves.
