### ISSUE TITLE
HipChat uses different server in username

### ISSUE THREAD

**Issue by brejoc** [errbotio/errbot#990]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.7
* OS version: Debian Jessie
* Python version: Python 3.4.2
* Using a virtual environment: yes

### Issue description

I've set up Errbot to connect to HipChat via XMPP. XMPP ist activated in HipChat. HipChat runs on the Server `1234-chat.myCompany.net`, while the usernames look like this: `mybot@myCompany.de`. It is not possible to connect to HipChat, because either the user username is wrong (when using `mybot@1234-chat.myCompany.net`) or the server can't be found (when using `mybot@myCompany.de`). 

### Steps to reproduce

1. Set up HipChat with usernames that are different from the actual Domain HipChat is listening on.
2. Activate XMPP in HipChat.
3. Generate token in HipChat und configure Errbot.
4. Try to connect to HipChat with Errbot.

### Additional info

I've tried to set `myCompany.de` to the IP of `1234-chat.myCompany.net` in `/etc/hosts` with no success.

**Comment by zoni** [comment]
To rule out issues with errbot specifically, could you try to connect that account to HipChat using a regular XMPP client (using Psi, Gajim or any other preferred client)? Are you able to connect correctly then?

**Comment by brejoc** [comment]
@zoni No, I can't login to HipChat via Jabber, because the server part of the JID is not actually pointing to `1234-chat.myCompany.net`, where the HipChat server is running. If I change the JID, the login fails, because then the username is wrong.

I've google some more and found this [thread](https://community.igniterealtime.org/thread/19537). There someone suggests to add some SRV dns entries to forward those requests to the actual server. Has someone tried that?

```
. 86400 CNAME chat.domain.com
xmpp-server.tcp.[domain.com]. 86400 IN SRV 5 0 5269 jabberserverhostname.
xmpp-client.tcp.[domain.com]. 86400 IN SRV 5 0 5222 jabberserverhostname.
jabber.tcp.[domain.com]. 86400 IN SRV 5 0 5269 jabberserverhostname.
```

**Comment by zoni** [comment]
Yes, you need to have proper XMPP SRV records set up for this to work. The last three records in your example look right. (Technically you only need `xmpp-client`, since there's no server to server for HipChat and the last one, `jabber`, is for backwards compatibility with very old clients).

Make note that if you stick to the 86400 TTL as in your example, any mistake will be cached for a day so I suggest trying with a low TTL and increasing it once you have it working. :smile: 

Since this is out of scope and not an issue with errbot itself I am going to close this issue, but if your bot still won't connect after setting up proper SRV records, please feel free to let us know and I will re-open.
